# Generated by Django 2.2.10 on 2020-06-17 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情'),
        ),
    ]
